#!/usr/bin/env python3

import os
import re
import sys
import hmac
import hashlib
import argparse
from cryptography.fernet import Fernet
import traceback
from dotenv import load_dotenv

load_dotenv()
fernet_key = os.getenv( "FERNET_KEY")

PASSWORD_LENGTH = 6

def fatal_error( msg ):
    
    print( f"Error: {msg}" )
    sys.exit(1)


def get_text_from_file( file ):
    
    try:
        return open( file ).read().strip()
    except Exception as e:
        fatal_error( f"can't read the file. {e}" )


def put_text_to_file( text ):

    try:
        with open( "ft_otp.key", "w" ) as file:
            file.write( text )
    except Exception as e:
        fatal_error( f"can't write in file. {e}" )


def check_initial_password_is_valid( initial_password ):
    
    if re.fullmatch( r"[0-9a-fA-F]+", initial_password ) == None or len( initial_password ) < 64:
        fatal_error( "initial password must be at least 64 hexadecimal characters" )


def encrypt_text( text ):

    fernet_object = Fernet( fernet_key.encode() )
    return fernet_object.encrypt( text.encode() )


def decrypt_text( text ):

    fernet_object = Fernet( fernet_key.encode() )
    return fernet_object.decrypt( text.encode() ).decode()


def store_initial_password( file ):
    
    initial_password = get_text_from_file( file )
    check_initial_password_is_valid( initial_password )
    encrypted_initial_password = encrypt_text( initial_password )
    put_text_to_file( encrypted_initial_password.decode() )


def generate_totp ( file ):
    
    counter = 1
    
    encrypted_initial_password = get_text_from_file( file )
    initial_password = decrypt_text( encrypted_initial_password )
    key_bytes = bytes.fromhex( initial_password )
    counter_in_bytes = counter.to_bytes( 8, byteorder = 'big' )
    hmac_hash = hmac.new( key_bytes, counter_in_bytes, hashlib.sha1 ).digest()
    offset = hmac_hash[-1] & 0x0F #00001111 take the last byte
    print( f"offset is {offset}" )
    # take 4 bits of last byte starting from offset
    truncated_4bytes = hmac_hash[ offset : offset+4 ]
    number_from_bytes = int.from_bytes( truncated_4bytes, byteorder = 'big' ) & 0x7FFFFFFF
    hotp_code = number_from_bytes % ( 10 ** PASSWORD_LENGTH )
    hotp_str = str( hotp_code ).zfill( PASSWORD_LENGTH )
    print( hotp_str )


def parse_args():

    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group( required=True )
    group.add_argument( '-g', nargs=1, help="python3 ft_otp.py -g key.txt" )
    group.add_argument( '-k', nargs=1, help="python3 ft_otp.py -k ft_otp.key" )

    return parser.parse_args()


def main():
    
    try:
        args = parse_args()
        if args.g != None:
            store_initial_password( args.g[0] )
        elif args.k != None:
            generate_totp( args.k[0] )
    except Exception as e:
        traceback.print_exc()
        sys.exit(1)
        #fatal_error( f"{e}" )


if __name__=="__main__":
    main()